[package]
name = "img2jxl"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25"  # Used for generic image manipulation and pixel formats
webp = "0.3.1"    # Used for WebP encoding
jxl-oxide = { version = "0.12", features = ["image"] } # Pure Rust JXL decoder
rayon = "1.8"