[package]
name = "atlas_creation"
version = "0.1.0"
edition = "2024"

[dependencies]
# The main crate for image manipulation (loading, saving, and processing pixels)
image = "0.25.9"
# For file system operations
glob = "0.3"